name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    env:
      SERVER_PORT: ${{ vars.SERVER_PORT }}
      SPEECH_REGION: ${{ vars.SPEECH_REGION }}
      VITE_SERVER_BASE_URL: ${{ vars.VITE_SERVER_BASE_URL }}
      MONGO_URI: ${{ secrets.MONGO_URI }}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      SPEECH_KEY: ${{ secrets.SPEECH_KEY }}
      OPENAI_KEY: ${{ secrets.OPENAI_KEY }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up environment variables
      run: |
        echo "SERVER_PORT=${SERVER_PORT}" >> $GITHUB_ENV
        echo "SPEECH_REGION=${SPEECH_REGION}" >> $GITHUB_ENV
        echo "VITE_SERVER_BASE_URL=${VITE_SERVER_BASE_URL}" >> $GITHUB_ENV
        echo "MONGO_URI=${MONGO_URI}" >> $GITHUB_ENV
        echo "JWT_SECRET_KEY=${JWT_SECRET_KEY}" >> $GITHUB_ENV
        echo "SPEECH_KEY=${SPEECH_KEY}" >> $GITHUB_ENV
        echo "OPENAI_KEY=${OPENAI_KEY}" >> $GITHUB_ENV

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies and build
      run: |
        npm ci
        npm run build --if-present

    - name: Restart PM2 process
      run: pm2 restart index
